# The file will produce result based on closing rank

# -*- coding: utf-8 -*-
"""//@PRIYANSH GUPTA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/priyanshgupta1998/Machine_learning/blob/master/Krisko_Assignmnet/coding.ipynb
"""



"""#Krisko Assignment"""


import pandas as pd    #import pandas library(inbulid python package)  used for data maniputation (like reading,writing file etc.)
data1 = pd.read_excel('Input-Rank-Cutoff-List.xlsx')   # read the dataset file( Excel)
data1.to_csv('Train.csv')  # convert this .xlsx file into .csv format for better understanding.

#print(data1.shape)  # check the order of the table ( rows x colmuns)

column = []  # create a empty list 
# create the header for the dataset
for i in range(data1.shape[1]):
  column.append('col_'+ str(i))
data = pd.read_csv('Train.csv' , names= column)
#print(data.shape)
#data.head()  # display first 5 rows of dataset/table

#arrange all the rows in proper seequence
data.reset_index(inplace=True)
#data.head()
data.drop('index' , axis =1 , inplace =True)

"""#Get the Branch Name"""
app =[]
for i in list(data[data['col_0']=='Branch Name '].index):
  app.append(i-1)
#print(len(app) , app)
collg = []
for i in app:
  collg.append(data['col_0'][i])
#print(len(collg) , collg)
#17 ['IIT Bombay', 'IIT Delhi', 'IIT Kharagpur', 'IIT Kanpur', 'IIT Madras', 'IIT Roorkee', 'IIT Guwahati', 'IIT Bhubaneshwar', 'IIT Mandi', 'IIT indore', 'IIT Hydrabad', 'IIT Jodhpur', 'IIT Gandhinagar', 'IIT Patna', 'IIT Ropar', 'IIT (BHU) Varanasi', 'ISM Dhanbad']


# create another column with the name of 'COLLEGE_NAME'.
virus = app.copy()
virus += [296]
for i in range(len(virus)-1):
  virus[i] = virus[i+1] - virus[i]
  
del virus[-1]
#print(len(virus) , virus)



# add all the college names 
col_name = []
for i in range(len(collg)):
  col_name+=[collg[i]]*virus[i]
#print(len(col_name))

data.insert(0,'College_Name',col_name)
#print(data.shape)
#data.head()
# Now new table has been created
				


#change all the header/column names accordingly			
data.rename(columns = {"col_0": "BRANCH_NAME" , "col_1":"GENERAL_OPEN" , "col_2":"GENERAL_CLOSE" , "col_3":"OBC_OPEN" ,"col_4":"OBC_CLOSE" , "col_5":"SC_OPEN"
                      ,"col_6":"SC_CLOSE", "col_7": "ST_OPEN" , "col_8":"ST_CLOSE"}  , inplace=True)



#Drop/delete all rows/lines which are having null values
data = data.dropna(how='any',axis=0)

data.drop(0 , axis =0 , inplace =True)  # delete first row (redundant)

# anrange data/table in order
data.reset_index(inplace=True)
data.drop('index' , axis =1 , inplace =True)

#print(data.shape)
#data.head(8)


# copy all data into anther table named 'df'
df = data.copy()

#here we have total 103 unique Branches 
#df['BRANCH_NAME'].nunique()

#df.info()  # it will provide all the information reagarding variable data type , null values , number of columns



# convert all the rank into integer/number from string 
df['GENERAL_OPEN'] = df['GENERAL_OPEN'].astype(int) 
df['GENERAL_CLOSE'] = df['GENERAL_CLOSE'].astype(int) 
df['OBC_OPEN'] = df['OBC_OPEN'].astype(int) 
df['OBC_CLOSE'] = df['OBC_CLOSE'].astype(int) 
df['SC_OPEN'] = df['SC_OPEN'].astype(int) 
df['SC_CLOSE'] = df['SC_CLOSE'].astype(int) 
df['ST_OPEN'] = df['ST_OPEN'].astype(int) 
df['ST_CLOSE'] = df['ST_CLOSE'].astype(int) 
#print(df.shape)
#df.info()




#df.describe() # descrip tion about dataset mean , medium , minimum, maximum , count  etc .for columns with numeric values 

#df.head(8)


#generate all  the ranks for all the colleges for each Department
#1.)for  general
rank_gen =[]
branch_gen = []
college_gen = []
categ_gen = []
for i in range(len(df)):
  app = []
  clg = []
  cat= []
  branch = []
  for j in range(list(df['GENERAL_OPEN'])[i] , list(df['GENERAL_CLOSE'])[i] + 1):
    branch.append(list(df['BRANCH_NAME'])[i])
    app.append(j)
    clg.append(list(df['College_Name'])[i])
    cat.append('GENERAL')
  rank_gen+=app
  branch_gen+=branch
  college_gen+=clg
  categ_gen+=cat


#2.)for obc
rank_obc =[]
branch_obc = []
college_obc = []
categ_obc = []
for i in range(len(df)):
  app = []
  clg = []
  cat= []
  branch = []
  for j in range(list(df['OBC_OPEN'])[i] , list(df['OBC_CLOSE'])[i] + 1):
    branch.append(list(df['BRANCH_NAME'])[i])
    app.append(j)
    clg.append(list(df['College_Name'])[i])
    cat.append('OBC')
  rank_obc+=app
  branch_obc+=branch
  college_obc+=clg
  categ_obc+=cat

#3.)for sc
rank_sc =[]
branch_sc = []
college_sc = []
categ_sc = []
for i in range(len(df)):
  app = []
  clg = []
  cat= []
  branch = []
  for j in range(list(df['SC_OPEN'])[i] , list(df['SC_CLOSE'])[i] + 1):
    branch.append(list(df['BRANCH_NAME'])[i])
    app.append(j)
    clg.append(list(df['College_Name'])[i])
    cat.append('SC')
  rank_sc+=app
  branch_sc+=branch
  college_sc+=clg
  categ_sc+=cat

#4.)for st
rank_st =[]
branch_st = []
college_st = []
categ_st = []
for i in range(len(df)):
  app = []
  clg = []
  cat= []
  branch = []
  for j in range(list(df['ST_OPEN'])[i] , list(df['ST_CLOSE'])[i] + 1):
    branch.append(list(df['BRANCH_NAME'])[i])
    app.append(j)
    clg.append(list(df['College_Name'])[i])
    cat.append('ST')
  rank_st+=app
  branch_st+=branch
  college_st+=clg
  categ_st+=cat


#Design datafrome for each catefory individually
#1.)for general
data_gen = pd.DataFrame()
data_gen['Department'] = branch_gen 
data_gen['INSTITUTES'] = college_gen
data_gen['CATEGORY'] = categ_gen 
data_gen['RANK_PREDICTOR'] = rank_gen 
#print(data_gen.shape)
#data_gen.head()


#2.)for obc
data_obc = pd.DataFrame()
data_obc['Department'] = branch_obc 
data_obc['INSTITUTES'] = college_obc
data_obc['CATEGORY'] = categ_obc
data_obc['RANK_PREDICTOR'] = rank_obc 
#print(data_obc.shape)
#data_obc.head()

#3.)for sc
data_sc = pd.DataFrame()
data_sc['Department'] = branch_sc
data_sc['INSTITUTES'] = college_sc
data_sc['CATEGORY'] = categ_sc
data_sc['RANK_PREDICTOR'] = rank_sc 
#print(data_sc.shape)
#data_sc.head()


#4.) for st
data_st= pd.DataFrame()
data_st['Department'] = branch_st
data_st['INSTITUTES'] = college_st
data_st['CATEGORY'] = categ_st
data_st['RANK_PREDICTOR'] = rank_st
#print(data_st.shape)
#data_st.head()



output_data = pd.concat([data_gen , data_obc , data_sc , data_st] ,ignore_index=True)
#print(output_data.shape)
#output_data.head()


output_data =  output_data[output_data['RANK_PREDICTOR']!=0]
#print(output_data.shape)
output_data.to_csv('OUTPUT.csv', index=False )













